<div class="field phone_number required">
    <label class="label" for="phone_number">
        <span><?= $block->escapeHtml(__('Phone number')) ?></span>
    </label>
    <div class="control">
        <input type="text" name="phone_number" id="phone_number" value="" title="<?= $block->escapeHtmlAttr(__('Phone number')) ?>" class="input-text" data-validate="{required:true}">
    </div>
</div>
<script type="text/javascript">
    document.addEventListener('DOMContentLoaded', function () {
        var phoneInput = document.getElementById('phone_number');

        phoneInput.addEventListener('input', function () {
            var value = phoneInput.value;

            if (value.startsWith('84')) {
                phoneInput.value = '0' + value.slice(2);
                if(value.length > 10) {
                    phoneInput.value = value.slice(0, 10);
                }
            });
    });
</script>
