<style>
    select {
        width: 150px;
    }
</style>
<?php $data = $block->getColorOptions(); ?>
<select id="select-color">
    <option value="">Mặc định</option>
    <?php foreach ($data as $key => $value) {?>
        <option value="<?= $value['color_code'] ?>"><?= $value['color'] ?></option>
    <?php }?>
</select>

<script>
    document.getElementById('select-color').addEventListener('change', () => {
        document.getElementById('html-body').style.background = document.getElementById('select-color').value;
    })
</script>
