<button id="hello-world" type="button">Hello World</button>
<button id="alert-model" type="button">Alert Model</button>
<button id="login-button" type="button">Model login</button>




<div id="login-modal" style="display: none;">
    <form>
        <label for="username">Username</label>
        <input type="text" id="username" name="username">

        <label for="password">Password</label>
        <input type="password" id="password" name="password">
    </form>
</div>




<script type="text/javascript">
    require(['customScript']);
</script>
