<?php
/** @var \Magenest\Movie\Block\Adminhtml\Report\Second $block */
?>
<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css">
<div style="width: 60%;float: right;">
    <h2>Detail</h2>
    <table class="table table-hover table-striper">
        <tbody>
        <tr>
            <td>Total customers</td>
            <td><?= $block->getCustomerCount() ?></td>
        </tr>
        <tr>
            <td>Total products</td>
            <td><?= $block->getProductCount() ?></td>
        </tr>
        <tr>
            <td>Total orders</td>
            <td><?= $block->getOrderCount() ?></td>
        </tr>
        <tr>
            <td>Total invoices</td>
            <td><?= $block->getInvoiceCount() ?></td>
        </tr>
        <tr>
            <td>Total creditmemos</td>
            <td><?= $block->getCreditmemoCount() ?></td>
        </tr>
        </tbody>
    </table>
</div>
